-- =============================================================================
-- VITE ET GOURMAND - Structure de la base de données
-- =============================================================================
-- SGBD          : PostgreSQL 16+
-- Base          : vite_et_gourmand
-- Généré depuis : schéma Doctrine ORM (entités src/Entity/)
--
-- Ce fichier reflète la structure réelle utilisée par l'application.
-- Il correspond aux migrations Doctrine :
--   - Version20260321102409 (création initiale)
--   - Version20260508000001 (titre_plat VARCHAR(50) -> VARCHAR(150))
--
-- Utilisation :
--   psql -U <utilisateur> -d vite_et_gourmand -f vite-et-gourmand.sql
-- =============================================================================


-- =============================================================================
-- 1. NETTOYAGE
-- CASCADE supprime automatiquement les contraintes de clés étrangères liées.
-- =============================================================================

DROP TABLE IF EXISTS plat_allergene CASCADE;
DROP TABLE IF EXISTS menu_plat CASCADE;
DROP TABLE IF EXISTS menu_image CASCADE;
DROP TABLE IF EXISTS avis CASCADE;
DROP TABLE IF EXISTS commande CASCADE;
DROP TABLE IF EXISTS menu CASCADE;
DROP TABLE IF EXISTS utilisateur CASCADE;
DROP TABLE IF EXISTS plat CASCADE;
DROP TABLE IF EXISTS horaire CASCADE;
DROP TABLE IF EXISTS allergene CASCADE;
DROP TABLE IF EXISTS regime CASCADE;
DROP TABLE IF EXISTS theme CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS messenger_messages CASCADE;


-- =============================================================================
-- 2. TABLES DE RÉFÉRENCE (sans dépendance)
-- =============================================================================

-- Rôles applicatifs : administrateur, employe, utilisateur, desactive
CREATE TABLE role (
    id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

-- Thèmes de menu : Noël, Pâques, Classique, Évènement
CREATE TABLE theme (
    id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

-- Régimes alimentaires : Classique, Végétarien, Végan, Sans Gluten
CREATE TABLE regime (
    id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

-- Les 14 allergènes réglementaires (règlement INCO n°1169/2011)
CREATE TABLE allergene (
    id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

-- Horaires d'ouverture affichés sur le site vitrine
CREATE TABLE horaire (
    id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    jour            VARCHAR(50) NOT NULL,
    heure_ouverture VARCHAR(50) DEFAULT NULL,
    heure_fermeture VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (id)
);

-- Plats composant les menus
CREATE TABLE plat (
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titre_plat VARCHAR(150) NOT NULL,
    photo      VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
);


-- =============================================================================
-- 3. TABLES PRINCIPALES
-- =============================================================================

-- Utilisateurs (clients, employés, administrateurs).
-- La colonne "roles" (JSON) est celle exploitée par le composant Security de
-- Symfony (ROLE_ADMIN, ROLE_EMPLOYE, ROLE_USER) ; "role_id" conserve le lien
-- métier vers la table role pour l'administration EasyAdmin.
CREATE TABLE utilisateur (
    id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email           VARCHAR(180) NOT NULL,
    roles           JSON NOT NULL,
    password        VARCHAR(255) NOT NULL,
    nom             VARCHAR(50) NOT NULL,
    prenom          VARCHAR(50) NOT NULL,
    telephone       VARCHAR(50) DEFAULT NULL,
    ville           VARCHAR(50) DEFAULT NULL,
    pays            VARCHAR(50) DEFAULT NULL,
    adresse_postale VARCHAR(255) DEFAULT NULL,
    role_id         INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON utilisateur (email);
CREATE INDEX IDX_1D1C63B3D60322AC ON utilisateur (role_id);

-- Menus proposés au catalogue
CREATE TABLE menu (
    id                      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titre                   VARCHAR(50) NOT NULL,
    nombre_personne_minimum INT NOT NULL,
    prix_par_personne       DOUBLE PRECISION NOT NULL,
    description             TEXT NOT NULL,
    conditions              TEXT DEFAULT NULL,
    quantite_restante       INT DEFAULT NULL,
    theme_id                INT NOT NULL,
    regime_id               INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_7D053A9359027487 ON menu (theme_id);
CREATE INDEX IDX_7D053A9335E7D534 ON menu (regime_id);

-- Photos associées à un menu (1 menu -> N images)
CREATE TABLE menu_image (
    id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url_image VARCHAR(255) NOT NULL,
    menu_id   INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_54912738CCD7E912 ON menu_image (menu_id);

-- Commandes de prestation traiteur
CREATE TABLE commande (
    id                   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero_commande      VARCHAR(50) NOT NULL,
    date_commande        DATE NOT NULL,
    date_prestation      DATE NOT NULL,
    heure_livraison      VARCHAR(50) DEFAULT NULL,
    lieu_prestation      VARCHAR(255) NOT NULL,
    prix_menu            DOUBLE PRECISION NOT NULL,
    nombre_personne      INT NOT NULL,
    prix_livraison       DOUBLE PRECISION NOT NULL,
    statut               VARCHAR(50) NOT NULL,
    pret_materiel        BOOLEAN NOT NULL,
    restitution_materiel BOOLEAN NOT NULL,
    motif_annulation     TEXT DEFAULT NULL,
    mode_contact_client  VARCHAR(50) DEFAULT NULL,
    utilisateur_id       INT NOT NULL,
    menu_id              INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_6EEAA67DFB88E14F ON commande (utilisateur_id);
CREATE INDEX IDX_6EEAA67DCCD7E912 ON commande (menu_id);

-- Avis client, rattaché à une commande précise (note de 1 à 5)
CREATE TABLE avis (
    id             INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note           SMALLINT NOT NULL,
    description    TEXT DEFAULT NULL,
    statut         VARCHAR(50) NOT NULL,
    utilisateur_id INT NOT NULL,
    commande_id    INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_8F91ABF0FB88E14F ON avis (utilisateur_id);
CREATE INDEX IDX_8F91ABF082EA2E54 ON avis (commande_id);


-- =============================================================================
-- 4. TABLES DE LIAISON (relations N:M)
-- =============================================================================

-- Un menu contient plusieurs plats, un plat peut figurer dans plusieurs menus
CREATE TABLE menu_plat (
    menu_id INT NOT NULL,
    plat_id INT NOT NULL,
    PRIMARY KEY (menu_id, plat_id)
);

CREATE INDEX IDX_E8775249CCD7E912 ON menu_plat (menu_id);
CREATE INDEX IDX_E8775249D73DB560 ON menu_plat (plat_id);

-- Un plat peut contenir plusieurs allergènes
CREATE TABLE plat_allergene (
    plat_id      INT NOT NULL,
    allergene_id INT NOT NULL,
    PRIMARY KEY (plat_id, allergene_id)
);

CREATE INDEX IDX_6FA44BBFD73DB560 ON plat_allergene (plat_id);
CREATE INDEX IDX_6FA44BBF4646AB2 ON plat_allergene (allergene_id);


-- =============================================================================
-- 5. CONTRAINTES DE CLÉS ÉTRANGÈRES
-- =============================================================================

ALTER TABLE utilisateur
    ADD CONSTRAINT FK_1D1C63B3D60322AC FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE;

ALTER TABLE menu
    ADD CONSTRAINT FK_7D053A9359027487 FOREIGN KEY (theme_id) REFERENCES theme (id) NOT DEFERRABLE;
ALTER TABLE menu
    ADD CONSTRAINT FK_7D053A9335E7D534 FOREIGN KEY (regime_id) REFERENCES regime (id) NOT DEFERRABLE;

ALTER TABLE menu_image
    ADD CONSTRAINT FK_54912738CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE;

ALTER TABLE commande
    ADD CONSTRAINT FK_6EEAA67DFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE;
ALTER TABLE commande
    ADD CONSTRAINT FK_6EEAA67DCCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE;

ALTER TABLE avis
    ADD CONSTRAINT FK_8F91ABF0FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE;
ALTER TABLE avis
    ADD CONSTRAINT FK_8F91ABF082EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE;

ALTER TABLE menu_plat
    ADD CONSTRAINT FK_E8775249CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE;
ALTER TABLE menu_plat
    ADD CONSTRAINT FK_E8775249D73DB560 FOREIGN KEY (plat_id) REFERENCES plat (id) ON DELETE CASCADE;

ALTER TABLE plat_allergene
    ADD CONSTRAINT FK_6FA44BBFD73DB560 FOREIGN KEY (plat_id) REFERENCES plat (id) ON DELETE CASCADE;
ALTER TABLE plat_allergene
    ADD CONSTRAINT FK_6FA44BBF4646AB2 FOREIGN KEY (allergene_id) REFERENCES allergene (id) ON DELETE CASCADE;


-- =============================================================================
-- 6. TABLE TECHNIQUE SYMFONY
-- File d'attente Messenger (envoi asynchrone des emails de confirmation).
-- =============================================================================

CREATE TABLE messenger_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    body         TEXT NOT NULL,
    headers      TEXT NOT NULL,
    queue_name   VARCHAR(190) NOT NULL,
    created_at   TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750
    ON messenger_messages (queue_name, available_at, delivered_at, id);


-- =============================================================================
-- 7. DONNÉES DE RÉFÉRENCE
-- Jeux de données indispensables au fonctionnement de l'application.
-- Les identifiants sont générés automatiquement (IDENTITY).
-- =============================================================================

INSERT INTO role (libelle) VALUES
    ('administrateur'),
    ('employe'),
    ('utilisateur'),
    ('desactive');

INSERT INTO theme (libelle) VALUES
    ('Noël'),
    ('Pâques'),
    ('Classique'),
    ('Évènement');

INSERT INTO regime (libelle) VALUES
    ('Classique'),
    ('Végétarien'),
    ('Végan'),
    ('Sans Gluten');

-- Les 14 allergènes à déclaration obligatoire
INSERT INTO allergene (libelle) VALUES
    ('Gluten'),
    ('Crustacés'),
    ('Œufs'),
    ('Poisson'),
    ('Arachides'),
    ('Soja'),
    ('Lait'),
    ('Fruits à coque'),
    ('Céleri'),
    ('Moutarde'),
    ('Sésame'),
    ('Sulfites'),
    ('Lupin'),
    ('Mollusques');

INSERT INTO horaire (jour, heure_ouverture, heure_fermeture) VALUES
    ('Lundi',    'Fermé', 'Fermé'),
    ('Mardi',    '09:00', '18:00'),
    ('Mercredi', '09:00', '18:00'),
    ('Jeudi',    '09:00', '18:00'),
    ('Vendredi', '09:00', '21:00'),
    ('Samedi',   '10:00', '21:00'),
    ('Dimanche', '10:00', '15:00');


-- =============================================================================
-- FIN DU SCRIPT
--
-- Remarque : les comptes utilisateurs ne sont pas inclus dans ce fichier.
-- Les mots de passe étant hachés (bcrypt), ils sont créés via les fixtures :
--   php bin/console doctrine:fixtures:load
-- =============================================================================
