-- Base de données Vite & Gourmand
-- SGBD : PostgreSQL
-- Ce script crée les tables et insère les données de base.
--
-- Pour l'exécuter :
--   psql -U <utilisateur> -d vite_et_gourmand -f vite-et-gourmand.sql


-- Suppression des tables si elles existent déjà

DROP TABLE IF EXISTS plat_allergene CASCADE;
DROP TABLE IF EXISTS menu_plat CASCADE;
DROP TABLE IF EXISTS menu_image CASCADE;
DROP TABLE IF EXISTS avis CASCADE;
DROP TABLE IF EXISTS commande CASCADE;
DROP TABLE IF EXISTS menu CASCADE;
DROP TABLE IF EXISTS utilisateur CASCADE;
DROP TABLE IF EXISTS plat CASCADE;
DROP TABLE IF EXISTS horaire CASCADE;
DROP TABLE IF EXISTS allergene CASCADE;
DROP TABLE IF EXISTS regime CASCADE;
DROP TABLE IF EXISTS theme CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS messenger_messages CASCADE;


-- Tables sans clé étrangère

CREATE TABLE role (
    id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE theme (
    id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE regime (
    id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE allergene (
    id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE horaire (
    id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    jour            VARCHAR(50) NOT NULL,
    heure_ouverture VARCHAR(50) DEFAULT NULL,
    heure_fermeture VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE plat (
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titre_plat VARCHAR(150) NOT NULL,
    photo      VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
);


-- Tables principales

CREATE TABLE utilisateur (
    id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email           VARCHAR(180) NOT NULL,
    roles           JSON NOT NULL,
    password        VARCHAR(255) NOT NULL,
    nom             VARCHAR(50) NOT NULL,
    prenom          VARCHAR(50) NOT NULL,
    telephone       VARCHAR(50) DEFAULT NULL,
    ville           VARCHAR(50) DEFAULT NULL,
    pays            VARCHAR(50) DEFAULT NULL,
    adresse_postale VARCHAR(255) DEFAULT NULL,
    role_id         INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON utilisateur (email);
CREATE INDEX IDX_1D1C63B3D60322AC ON utilisateur (role_id);

CREATE TABLE menu (
    id                      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titre                   VARCHAR(50) NOT NULL,
    nombre_personne_minimum INT NOT NULL,
    prix_par_personne       DOUBLE PRECISION NOT NULL,
    description             TEXT NOT NULL,
    conditions              TEXT DEFAULT NULL,
    quantite_restante       INT DEFAULT NULL,
    theme_id                INT NOT NULL,
    regime_id               INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_7D053A9359027487 ON menu (theme_id);
CREATE INDEX IDX_7D053A9335E7D534 ON menu (regime_id);

-- Galerie photo d'un menu
CREATE TABLE menu_image (
    id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url_image VARCHAR(255) NOT NULL,
    menu_id   INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_54912738CCD7E912 ON menu_image (menu_id);

CREATE TABLE commande (
    id                   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero_commande      VARCHAR(50) NOT NULL,
    date_commande        DATE NOT NULL,
    date_prestation      DATE NOT NULL,
    heure_livraison      VARCHAR(50) DEFAULT NULL,
    lieu_prestation      VARCHAR(255) NOT NULL,
    prix_menu            DOUBLE PRECISION NOT NULL,
    nombre_personne      INT NOT NULL,
    prix_livraison       DOUBLE PRECISION NOT NULL,
    statut               VARCHAR(50) NOT NULL,
    pret_materiel        BOOLEAN NOT NULL,
    restitution_materiel BOOLEAN NOT NULL,
    motif_annulation     TEXT DEFAULT NULL,
    mode_contact_client  VARCHAR(50) DEFAULT NULL,
    utilisateur_id       INT NOT NULL,
    menu_id              INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_6EEAA67DFB88E14F ON commande (utilisateur_id);
CREATE INDEX IDX_6EEAA67DCCD7E912 ON commande (menu_id);

-- Avis laissé par un client sur une commande terminée
CREATE TABLE avis (
    id             INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note           SMALLINT NOT NULL,
    description    TEXT DEFAULT NULL,
    statut         VARCHAR(50) NOT NULL,
    utilisateur_id INT NOT NULL,
    commande_id    INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_8F91ABF0FB88E14F ON avis (utilisateur_id);
CREATE INDEX IDX_8F91ABF082EA2E54 ON avis (commande_id);


-- Tables de liaison pour les relations plusieurs à plusieurs

-- Un menu contient plusieurs plats, un plat peut être dans plusieurs menus
CREATE TABLE menu_plat (
    menu_id INT NOT NULL,
    plat_id INT NOT NULL,
    PRIMARY KEY (menu_id, plat_id)
);

CREATE INDEX IDX_E8775249CCD7E912 ON menu_plat (menu_id);
CREATE INDEX IDX_E8775249D73DB560 ON menu_plat (plat_id);

-- Un plat peut contenir plusieurs allergènes
CREATE TABLE plat_allergene (
    plat_id      INT NOT NULL,
    allergene_id INT NOT NULL,
    PRIMARY KEY (plat_id, allergene_id)
);

CREATE INDEX IDX_6FA44BBFD73DB560 ON plat_allergene (plat_id);
CREATE INDEX IDX_6FA44BBF4646AB2 ON plat_allergene (allergene_id);


-- Clés étrangères

ALTER TABLE utilisateur
    ADD CONSTRAINT FK_1D1C63B3D60322AC FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE;

ALTER TABLE menu
    ADD CONSTRAINT FK_7D053A9359027487 FOREIGN KEY (theme_id) REFERENCES theme (id) NOT DEFERRABLE;
ALTER TABLE menu
    ADD CONSTRAINT FK_7D053A9335E7D534 FOREIGN KEY (regime_id) REFERENCES regime (id) NOT DEFERRABLE;

ALTER TABLE menu_image
    ADD CONSTRAINT FK_54912738CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE;

ALTER TABLE commande
    ADD CONSTRAINT FK_6EEAA67DFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE;
ALTER TABLE commande
    ADD CONSTRAINT FK_6EEAA67DCCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE;

ALTER TABLE avis
    ADD CONSTRAINT FK_8F91ABF0FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE;
ALTER TABLE avis
    ADD CONSTRAINT FK_8F91ABF082EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE;

ALTER TABLE menu_plat
    ADD CONSTRAINT FK_E8775249CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE;
ALTER TABLE menu_plat
    ADD CONSTRAINT FK_E8775249D73DB560 FOREIGN KEY (plat_id) REFERENCES plat (id) ON DELETE CASCADE;

ALTER TABLE plat_allergene
    ADD CONSTRAINT FK_6FA44BBFD73DB560 FOREIGN KEY (plat_id) REFERENCES plat (id) ON DELETE CASCADE;
ALTER TABLE plat_allergene
    ADD CONSTRAINT FK_6FA44BBF4646AB2 FOREIGN KEY (allergene_id) REFERENCES allergene (id) ON DELETE CASCADE;


-- Table utilisée par Symfony pour la file d'envoi des mails

CREATE TABLE messenger_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    body         TEXT NOT NULL,
    headers      TEXT NOT NULL,
    queue_name   VARCHAR(190) NOT NULL,
    created_at   TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750
    ON messenger_messages (queue_name, available_at, delivered_at, id);


-- Données de base

INSERT INTO role (libelle) VALUES
    ('administrateur'),
    ('employe'),
    ('utilisateur'),
    ('desactive');

INSERT INTO theme (libelle) VALUES
    ('Noël'),
    ('Pâques'),
    ('Classique'),
    ('Évènement');

INSERT INTO regime (libelle) VALUES
    ('Classique'),
    ('Végétarien'),
    ('Végan'),
    ('Sans Gluten');

-- Les 14 allergènes à déclaration obligatoire
INSERT INTO allergene (libelle) VALUES
    ('Gluten'),
    ('Crustacés'),
    ('Œufs'),
    ('Poisson'),
    ('Arachides'),
    ('Soja'),
    ('Lait'),
    ('Fruits à coque'),
    ('Céleri'),
    ('Moutarde'),
    ('Sésame'),
    ('Sulfites'),
    ('Lupin'),
    ('Mollusques');

INSERT INTO horaire (jour, heure_ouverture, heure_fermeture) VALUES
    ('Lundi',    'Fermé', 'Fermé'),
    ('Mardi',    '09:00', '18:00'),
    ('Mercredi', '09:00', '18:00'),
    ('Jeudi',    '09:00', '18:00'),
    ('Vendredi', '09:00', '21:00'),
    ('Samedi',   '10:00', '21:00'),
    ('Dimanche', '10:00', '15:00');

-- Les comptes utilisateurs ne sont pas dans ce fichier :
-- les mots de passe sont hachés, ils sont créés par les fixtures.
